### ISSUE TITLE
Extract unit sprites

### ISSUE THREAD

**Issue by bmustiata** [ciplogic/TilePainter#1]
I'm trying to see if AI could be used to interpolate unit frames. In the current project, all I see is a rendering of a map. Is it possible to extract individual unit animation frames? 

i.e. something like this: https://www.spriters-resource.com/pc_computer/heroesofmightandmagic2/?source=genre

But for an individual character/animation to extract individual images.

**Comment by ciplogic** [comment]
Hello @bmustiata, I think that you need to work with method:

```
class AggFile {
public static IcnSprite RenderICNSprite(Agg agg, int icn, int index) {
(...)
}
}
```
if you want to use quick and dirty extraction.

The AGG file ("heroes2.agg") is included in your Heroes 2 distribution ("DATA/HEROES2.AGG").

The pseudocode would look like following:
```
psvm(args){
Agg agg = Agg.get();
IntStream.range(0, IcnKind.LASTICN).
  forEach(idxIcn -> 
  {
    var spritesPerIcn = agg.IcnSpriteCount(idxIcn);
    IntStream.range(0, spritesPerIcn).
  forEach(idxAnimationFrame -> 
    var sprite = agg.GetIcn(icn,idxAnimationFrame);
    //sprite has 2 images that can be saved to disk:
    sprite.first.saveToFile(new File("pic"+idxIcn+"_"+idxAnimationFrame+".png"));
    // it makes sure there is a backing image. 
    if (sprite.second.Width != 0){
      sprite.second.saveToFile(new File("back_pic"+idxIcn+"_"+idxAnimationFrame+".png"));
    }
  });
}
```

**Comment by bmustiata** [comment]
Got it, thanks.
